### PR TITLE
Fix error message

### LINKED ISSUE #170: [PE-D][Tester C] Incorrect Error Message For Delete
Noticed that when the given index is larger than the total number of clients, the error messages are given as follows:

But when the input index is very large, the error messages suggest that the command format is invalid, which is not true since the given command is in the correct format:

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: PallonCX/ped#2

### LINKED ISSUE #179: [PE-D][Tester C] Incorrect Error Message For Add Meeting
Noticed that when the given index is larger than the total number of clients, the error messages are given as follows:

But when the input index is very large, the error messages suggest that the command format is invalid, which is not true since the given command is in the correct format:

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: PallonCX/ped#4

### LINKED ISSUE #199: [PE-D][Tester C] Incorrect Error Message For Edit Meeting
Noticed that when the given index is larger than the total number of clients, the error messages are given as follows:

But when the input index is very large, the error messages suggest that the command format is invalid, which is not true since the given command is in the correct format:

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: PallonCX/ped#10

### LINKED ISSUE #209: [PE-D][Tester C] Incorrect Error Message For Delete Meeting
Noticed that when the given index is larger than the total number of clients, the error messages are given as follows:

But when the input index is very large, the error messages suggest that the command format is invalid, which is not true since the given command is in the correct format:

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: PallonCX/ped#13

### PR DESCRIPTION
**Pull request by sethteo**
Fixes #179 
Fixes #199 
Fixes #209
Fixes #170 

Changed error messages to display the invalid index correctly but did not change code if integer overflow.

### CODE REVIEW

**Review by chewbum — COMMENTED** [review]
LGTM!

File: src/main/java/seedu/address/logic/commands/AddMeetingCommand.java [hunk 1]
```diff
@@ -75,7 +75,8 @@ public CommandResult execute(Model model) throws CommandException {
         List<Person> lastShownList = model.getFilteredPersonList();
 
         if (clientIndex.getZeroBased() >= lastShownList.size()) {
-            throw new CommandException(Messages.MESSAGE_INVALID_PERSON_DISPLAYED_INDEX);
+            throw new CommandException(String.format(Messages.MESSAGE_INVALID_PERSON_DISPLAYED_INDEX,
+                    clientIndex.getOneBased()));
```
Comment (itstrueitstrueitsrealitsreal) [inline src/main/java/seedu/address/logic/commands/AddMeetingCommand.java:79]: Well done Seth!

**Review by itstrueitstrueitsrealitsreal — COMMENTED** [review]
Looks Good To Me! 🥇
